# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCbyECf8QYrMfAuZbFvPSAXGbrtpQ4-w
"""

# Gerekli kütüphaneleri yükleme
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# CSV dosyasını oku
df = pd.read_csv("freelancer_earnings_bd.csv")

# Eksik verileri kontrol et ve doldur
df.fillna(0, inplace=True)

# Genel İstatistikler
summary = {
    "Toplam Freelancer Sayısı": df["Freelancer_ID"].nunique(),
    "Toplam İş Sayısı": df["Job_Completed"].sum(),
    "Toplam Kazanç (USD)": df["Earnings_USD"].sum(),
    "Ortalama Saatlik Ücret (USD)": round(df["Hourly_Rate"].mean(), 2),
    "Ortalama İş Başarı Oranı (%)": round(df["Job_Success_Rate"].mean(), 2),
    "Ortalama Müşteri Puanı": round(df["Client_Rating"].mean(), 2),
    "Ortalama İş Süresi (Gün)": round(df["Job_Duration_Days"].mean(), 2),
    "Ortalama Tekrar İşe Alım Oranı (%)": round(df["Rehire_Rate"].mean(), 2),
    "Ortalama Pazarlama Harcaması (USD)": round(df["Marketing_Spend"].mean(), 2),
}

# En Popüler İş Kategorileri
top_categories = df["Job_Category"].value_counts().head(5)

# En Çok Kazandıran Platformlar
top_platforms = df.groupby("Platform")["Earnings_USD"].sum().sort_values(ascending=False).head(5)

# Deneyim Seviyesine Göre Ortalama Kazançlar
top_experience = df.groupby("Experience_Level")["Earnings_USD"].mean().sort_values(ascending=False)

# Saatlik Ücretin İş Başarı Oranına Etkisi
plt.figure(figsize=(10, 5))
sns.scatterplot(x=df["Hourly_Rate"], y=df["Job_Success_Rate"], alpha=0.5)
plt.xlabel("Saatlik Ücret (USD)")
plt.ylabel("İş Başarı Oranı (%)")
plt.title("Saatlik Ücretin İş Başarı Oranına Etkisi")
plt.show()

# Müşteri Puanı ve Kazanç Arasındaki İlişki
plt.figure(figsize=(10, 5))
sns.scatterplot(x=df["Client_Rating"], y=df["Earnings_USD"], alpha=0.5)
plt.xlabel("Müşteri Puanı")
plt.ylabel("Kazanç (USD)")
plt.title("Müşteri Puanı ve Kazanç Arasındaki İlişki")
plt.show()

# İş Sayısı ve Kazanç Arasındaki İlişki
plt.figure(figsize=(10, 5))
sns.scatterplot(x=df["Job_Completed"], y=df["Earnings_USD"], alpha=0.5)
plt.xlabel("Tamamlanan İş Sayısı")
plt.ylabel("Kazanç (USD)")
plt.title("Tamamlanan İş Sayısı ve Kazanç Arasındaki İlişki")
plt.show()

# Sonuçları Yazdır
print("\n--- Genel İstatistikler ---")
for key, value in summary.items():
    print(f"{key}: {value}")

print("\n--- En Popüler İş Kategorileri ---")
print(top_categories)

print("\n--- En Çok Kazandıran Platformlar ---")
print(top_platforms)

print("\n--- Deneyim Seviyesine Göre Ortalama Kazançlar ---")
print(top_experience)

"""# Analiz Sonuçları

Analiz Sonuçları:
1. En fazla kazanç sağlayan platformlar belirlenmiş olup bu platformlarda çalışan freelancerlar daha yüksek gelir elde etmektedir.
2. İş başarı oranı yüksek olan freelancerların genellikle daha fazla kazanç sağladığı gözlemlenmiştir.
3. Deneyim seviyesi yükseldikçe kazanç oranında belirgin bir artış olduğu görülmektedir.
4. Saatlik ücretin artması, iş başarı oranı ile doğrudan bağlantılı olabilir ancak bazı platformlarda bu ilişki daha zayıf gözükmektedir.
5. Müşteri puanı arttıkça freelancerların daha yüksek kazanç elde ettiği tespit edilmiştir.
6. Tamamlanan iş sayısı arttıkça kazanç da artmakta ancak belirli bir noktadan sonra doygunluğa ulaşmaktadır.
"""